# Generated by Django 5.0.3 on 2024-04-09 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('idalcohol', models.IntegerField(db_column='idAlcohol', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alcohol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idcategory', models.IntegerField(db_column='idCategory', primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('idcocktail', models.BigIntegerField(db_column='idCocktail', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'cocktail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('idingredient', models.IntegerField(db_column='idIngredient', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingredient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keep',
            fields=[
                ('idkeep', models.BigIntegerField(db_column='idKeep', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'keep',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('idkeyword', models.IntegerField(db_column='idKeyword', primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('idlike', models.BigIntegerField(db_column='idLike', primary_key=True, serialize=False)),
                ('accumulate', models.BigIntegerField(blank=True, null=True)),
                ('weekly', models.IntegerField(blank=True, null=True)),
                ('week', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'like',
                'db_table_comment': '\t\t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MakingImages',
            fields=[
                ('idmaking_images', models.BigIntegerField(db_column='idMaking_Images', primary_key=True, serialize=False)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'making_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MakingVideo',
            fields=[
                ('idmaking_video', models.BigIntegerField(db_column='idMaking_video', primary_key=True, serialize=False)),
                ('video_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'making_video',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('idmember', models.BigAutoField(db_column='idMember', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('pwd', models.CharField(blank=True, max_length=20, null=True)),
                ('nickname', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('qual', models.IntegerField(blank=True, null=True)),
                ('introduce', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('idpost', models.BigIntegerField(db_column='idPost', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('view', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('idreview', models.IntegerField(db_column='idReview', primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('idseason', models.IntegerField(db_column='idSeason', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'season',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('idstore', models.IntegerField(db_column='idStore', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'store',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('idtimes', models.IntegerField(db_column='idTimes', primary_key=True, serialize=False)),
                ('when', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'times',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wheather',
            fields=[
                ('idwheather', models.IntegerField(db_column='idWheather', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'wheather',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CocktailHasAlcohol',
            fields=[
                ('cocktail_idcocktail', models.OneToOneField(db_column='Cocktail_idCocktail', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='caki_app.cocktail')),
            ],
            options={
                'db_table': 'cocktail_has_alcohol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CocktailHasIngredient',
            fields=[
                ('cocktail_idcocktail', models.OneToOneField(db_column='Cocktail_idCocktail', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='caki_app.cocktail')),
            ],
            options={
                'db_table': 'cocktail_has_ingredient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientHasStore',
            fields=[
                ('ingredient_idingredient', models.OneToOneField(db_column='Ingredient_idIngredient', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='caki_app.ingredient')),
            ],
            options={
                'db_table': 'ingredient_has_store',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoreHasAlcohol',
            fields=[
                ('store_idstore', models.OneToOneField(db_column='Store_idStore', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='caki_app.store')),
            ],
            options={
                'db_table': 'store_has_alcohol',
                'managed': False,
            },
        ),
    ]
